# Generated by Django 3.1.4 on 2020-12-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
